package one.two.three.tools;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

// Regenerates get-product-multi-env.feature from csv/environ.csv before every test run
// (wired via exec-maven-plugin in pom.xml), so the CSV is the single source of truth
// for the Scenario Outline's Examples table.
public class FeatureFileGenerator {

    private static final Path CSV_PATH = Paths.get("src/test/resources/csv/environ.csv");
    private static final Path OUTPUT_PATH = Paths.get("target/generated-features/get-product-multi-env.feature");

    public static void main(String[] args) throws Exception {
        generate(CSV_PATH, OUTPUT_PATH);
    }

    static void generate(Path csvPath, Path outputPath) throws Exception {
        List<String> lines = Files.readAllLines(csvPath).stream()
            .filter(line -> !line.isBlank())
            .toList();

        if (lines.isEmpty()) {
            throw new IllegalStateException("CSV file '" + csvPath + "' has no rows");
        }

        String[] columns = lines.get(0).split(",", -1);
        List<String> dataRows = lines.subList(1, lines.size());

        StringBuilder feature = new StringBuilder();
        feature.append("# Auto-generated by FeatureFileGenerator from ").append(csvPath).append(" — do not edit by hand.\n");
        feature.append("@system @regression @multi-env\n");
        feature.append("Feature: GET Product across environments (data-driven from environ.csv)\n\n");
        feature.append("  Scenario Outline: Validate product data for <baseurl><endpoint>\n");
        feature.append("    Given the base URL is \"https://<baseurl>\"\n");
        feature.append("    When I send a GET request to \"<endpoint>\"\n");
        feature.append("    Then the response status should be <httpStatusCode>\n");
        feature.append("    And the value of the element \"<jsonPath1>\" is \"<value1>\"\n");
        feature.append("    And the value of the element \"<jsonpath2>\" is \"<value2>\"\n\n");
        feature.append("    Examples:\n");
        feature.append(row(columns));
        for (String dataRow : dataRows) {
            feature.append(row(dataRow.split(",", -1)));
        }

        Files.createDirectories(outputPath.getParent());
        Files.writeString(outputPath, feature.toString());
        System.out.println("[FeatureFileGenerator] Generated " + outputPath + " from " + csvPath
            + " (" + dataRows.size() + " row(s))");
    }

    private static String row(String[] cells) {
        StringBuilder sb = new StringBuilder("      |");
        for (String cell : cells) {
            sb.append(' ').append(cell.trim()).append(" |");
        }
        return sb.append('\n').toString();
    }
}
